package lcb.com.pe.domain;
// Generated 21/02/2017 12:52:07 PM by Hibernate Tools 5.0.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name = "Menu", schema = "dbo", catalog = "LCB_SECURITY")
public class Menu implements java.io.Serializable {

	private Integer idMenu;
	private Sistema sistema;
	private Integer idParent;
	private String descripcion;
	private String uri;
	private short nivel;
	private short orden;
	private String icono;
	private Date fechaRegistro;
	private Set<PermisoMenu> permisoMenus = new HashSet<PermisoMenu>(0);

	public Menu() {
	}

	public Menu(Sistema sistema, String descripcion, short nivel, short orden, Date fechaRegistro) {
		this.sistema = sistema;
		this.descripcion = descripcion;
		this.nivel = nivel;
		this.orden = orden;
		this.fechaRegistro = fechaRegistro;
	}

	public Menu(Sistema sistema, Integer idParent, String descripcion, String uri, short nivel, short orden,
			String icono, Date fechaRegistro, Set<PermisoMenu> permisoMenus) {
		this.sistema = sistema;
		this.idParent = idParent;
		this.descripcion = descripcion;
		this.uri = uri;
		this.nivel = nivel;
		this.orden = orden;
		this.icono = icono;
		this.fechaRegistro = fechaRegistro;
		this.permisoMenus = permisoMenus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_menu", unique = true, nullable = false)
	public Integer getIdMenu() {
		return this.idMenu;
	}

	public void setIdMenu(Integer idMenu) {
		this.idMenu = idMenu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_sistema", nullable = false)
	public Sistema getSistema() {
		return this.sistema;
	}

	public void setSistema(Sistema sistema) {
		this.sistema = sistema;
	}

	@Column(name = "id_parent")
	public Integer getIdParent() {
		return this.idParent;
	}

	public void setIdParent(Integer idParent) {
		this.idParent = idParent;
	}

	@Column(name = "descripcion", nullable = false, length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "uri", length = 100)
	public String getUri() {
		return this.uri;
	}

	public void setUri(String uri) {
		this.uri = uri;
	}

	@Column(name = "nivel", nullable = false)
	public short getNivel() {
		return this.nivel;
	}

	public void setNivel(short nivel) {
		this.nivel = nivel;
	}

	@Column(name = "orden", nullable = false)
	public short getOrden() {
		return this.orden;
	}

	public void setOrden(short orden) {
		this.orden = orden;
	}

	@Column(name = "icono", length = 50)
	public String getIcono() {
		return this.icono;
	}

	public void setIcono(String icono) {
		this.icono = icono;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_registro", nullable = false, length = 23)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menu")
	public Set<PermisoMenu> getPermisoMenus() {
		return this.permisoMenus;
	}

	public void setPermisoMenus(Set<PermisoMenu> permisoMenus) {
		this.permisoMenus = permisoMenus;
	}

}
