package lcb.com.pe.domain;
// Generated 21/02/2017 12:52:07 PM by Hibernate Tools 5.0.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OauthAccessToken generated by hbm2java
 */
@Entity
@Table(name = "oauth_access_token", schema = "dbo", catalog = "LCB_SECURITY")
public class OauthAccessToken implements java.io.Serializable {

	private String tokenId;
	private String token;
	private String authenticationId;
	private String userName;
	private String clientId;
	private String authentication;
	private String refreshToken;

	public OauthAccessToken() {
	}

	public OauthAccessToken(String tokenId, String token, String authenticationId, String userName, String clientId,
			String authentication, String refreshToken) {
		this.tokenId = tokenId;
		this.token = token;
		this.authenticationId = authenticationId;
		this.userName = userName;
		this.clientId = clientId;
		this.authentication = authentication;
		this.refreshToken = refreshToken;
	}

	@Id
	@Column(name = "token_id", length = 256)
	public String getTokenId() {
		return this.tokenId;
	}

	public void setTokenId(String tokenId) {
		this.tokenId = tokenId;
	}

	@Column(name = "token")
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@Column(name = "authentication_id", length = 256)
	public String getAuthenticationId() {
		return this.authenticationId;
	}

	public void setAuthenticationId(String authenticationId) {
		this.authenticationId = authenticationId;
	}

	@Column(name = "user_name", length = 256)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "client_id", length = 256)
	public String getClientId() {
		return this.clientId;
	}

	public void setClientId(String clientId) {
		this.clientId = clientId;
	}

	@Column(name = "authentication")
	public String getAuthentication() {
		return this.authentication;
	}

	public void setAuthentication(String authentication) {
		this.authentication = authentication;
	}

	@Column(name = "refresh_token", length = 256)
	public String getRefreshToken() {
		return this.refreshToken;
	}

	public void setRefreshToken(String refreshToken) {
		this.refreshToken = refreshToken;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OauthAccessToken))
			return false;
		OauthAccessToken castOther = (OauthAccessToken) other;

		return ((this.getTokenId() == castOther.getTokenId()) || (this.getTokenId() != null
				&& castOther.getTokenId() != null && this.getTokenId().equals(castOther.getTokenId())))
				&& ((this.getToken() == castOther.getToken()) || (this.getToken() != null
						&& castOther.getToken() != null && this.getToken().equals(castOther.getToken())))
				&& ((this.getAuthenticationId() == castOther.getAuthenticationId())
						|| (this.getAuthenticationId() != null && castOther.getAuthenticationId() != null
								&& this.getAuthenticationId().equals(castOther.getAuthenticationId())))
				&& ((this.getUserName() == castOther.getUserName()) || (this.getUserName() != null
						&& castOther.getUserName() != null && this.getUserName().equals(castOther.getUserName())))
				&& ((this.getClientId() == castOther.getClientId()) || (this.getClientId() != null
						&& castOther.getClientId() != null && this.getClientId().equals(castOther.getClientId())))
				&& ((this.getAuthentication() == castOther.getAuthentication())
						|| (this.getAuthentication() != null && castOther.getAuthentication() != null
								&& this.getAuthentication().equals(castOther.getAuthentication())))
				&& ((this.getRefreshToken() == castOther.getRefreshToken())
						|| (this.getRefreshToken() != null && castOther.getRefreshToken() != null
								&& this.getRefreshToken().equals(castOther.getRefreshToken())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTokenId() == null ? 0 : this.getTokenId().hashCode());
		result = 37 * result + (getToken() == null ? 0 : this.getToken().hashCode());
		result = 37 * result + (getAuthenticationId() == null ? 0 : this.getAuthenticationId().hashCode());
		result = 37 * result + (getUserName() == null ? 0 : this.getUserName().hashCode());
		result = 37 * result + (getClientId() == null ? 0 : this.getClientId().hashCode());
		result = 37 * result + (getAuthentication() == null ? 0 : this.getAuthentication().hashCode());
		result = 37 * result + (getRefreshToken() == null ? 0 : this.getRefreshToken().hashCode());
		return result;
	}

}
