package lcb.com.pe.domain;
// Generated 21/02/2017 12:52:07 PM by Hibernate Tools 5.0.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PermisoMenuId generated by hbm2java
 */
@Embeddable
public class PermisoMenuId implements java.io.Serializable {

	private short idRol;
	private int idMenu;

	public PermisoMenuId() {
	}

	public PermisoMenuId(short idRol, int idMenu) {
		this.idRol = idRol;
		this.idMenu = idMenu;
	}

	@Column(name = "id_rol", nullable = false)
	public short getIdRol() {
		return this.idRol;
	}

	public void setIdRol(short idRol) {
		this.idRol = idRol;
	}

	@Column(name = "id_menu", nullable = false)
	public int getIdMenu() {
		return this.idMenu;
	}

	public void setIdMenu(int idMenu) {
		this.idMenu = idMenu;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PermisoMenuId))
			return false;
		PermisoMenuId castOther = (PermisoMenuId) other;

		return (this.getIdRol() == castOther.getIdRol()) && (this.getIdMenu() == castOther.getIdMenu());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdRol();
		result = 37 * result + this.getIdMenu();
		return result;
	}

}
