package lcb.com.pe.domain;
// Generated 21/02/2017 12:52:07 PM by Hibernate Tools 5.0.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PermisoRepositorio generated by hbm2java
 */
@Entity
@Table(name = "Permiso_Repositorio", schema = "dbo", catalog = "LCB_SECURITY")
public class PermisoRepositorio implements java.io.Serializable {

	private PermisoRepositorioId id;
	private Repositorio repositorio;
	private Rol rol;
	private boolean canCreate;
	private boolean canRead;
	private boolean canUpdate;
	private boolean canDelete;

	public PermisoRepositorio() {
	}

	public PermisoRepositorio(PermisoRepositorioId id, Repositorio repositorio, Rol rol, boolean canCreate,
			boolean canRead, boolean canUpdate, boolean canDelete) {
		this.id = id;
		this.repositorio = repositorio;
		this.rol = rol;
		this.canCreate = canCreate;
		this.canRead = canRead;
		this.canUpdate = canUpdate;
		this.canDelete = canDelete;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idRol", column = @Column(name = "id_rol", nullable = false)),
			@AttributeOverride(name = "idRepositorio", column = @Column(name = "id_repositorio", nullable = false)) })
	public PermisoRepositorioId getId() {
		return this.id;
	}

	public void setId(PermisoRepositorioId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_repositorio", nullable = false, insertable = false, updatable = false)
	public Repositorio getRepositorio() {
		return this.repositorio;
	}

	public void setRepositorio(Repositorio repositorio) {
		this.repositorio = repositorio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_rol", nullable = false, insertable = false, updatable = false)
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	@Column(name = "can_create", nullable = false)
	public boolean isCanCreate() {
		return this.canCreate;
	}

	public void setCanCreate(boolean canCreate) {
		this.canCreate = canCreate;
	}

	@Column(name = "can_read", nullable = false)
	public boolean isCanRead() {
		return this.canRead;
	}

	public void setCanRead(boolean canRead) {
		this.canRead = canRead;
	}

	@Column(name = "can_update", nullable = false)
	public boolean isCanUpdate() {
		return this.canUpdate;
	}

	public void setCanUpdate(boolean canUpdate) {
		this.canUpdate = canUpdate;
	}

	@Column(name = "can_delete", nullable = false)
	public boolean isCanDelete() {
		return this.canDelete;
	}

	public void setCanDelete(boolean canDelete) {
		this.canDelete = canDelete;
	}

}
