package lcb.com.pe.domain;
// Generated 21/02/2017 12:52:07 PM by Hibernate Tools 5.0.3.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PermisoMenu generated by hbm2java
 */
@Entity
@Table(name = "Permiso_Menu", schema = "dbo", catalog = "LCB_SECURITY")
public class PermisoMenu implements java.io.Serializable {

	private PermisoMenuId id;
	private Menu menu;
	private Rol rol;
	private boolean canCreate;
	private boolean canRead;
	private boolean canUpdate;
	private boolean canDelete;
	private Date fechaRegistro;
	private String usuarioRegistro;
	private Date fechaModifico;
	private String usuarioModifico;

	public PermisoMenu() {
	}

	public PermisoMenu(PermisoMenuId id, Menu menu, Rol rol, boolean canCreate, boolean canRead, boolean canUpdate,
			boolean canDelete, Date fechaRegistro, String usuarioRegistro) {
		this.id = id;
		this.menu = menu;
		this.rol = rol;
		this.canCreate = canCreate;
		this.canRead = canRead;
		this.canUpdate = canUpdate;
		this.canDelete = canDelete;
		this.fechaRegistro = fechaRegistro;
		this.usuarioRegistro = usuarioRegistro;
	}

	public PermisoMenu(PermisoMenuId id, Menu menu, Rol rol, boolean canCreate, boolean canRead, boolean canUpdate,
			boolean canDelete, Date fechaRegistro, String usuarioRegistro, Date fechaModifico, String usuarioModifico) {
		this.id = id;
		this.menu = menu;
		this.rol = rol;
		this.canCreate = canCreate;
		this.canRead = canRead;
		this.canUpdate = canUpdate;
		this.canDelete = canDelete;
		this.fechaRegistro = fechaRegistro;
		this.usuarioRegistro = usuarioRegistro;
		this.fechaModifico = fechaModifico;
		this.usuarioModifico = usuarioModifico;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idRol", column = @Column(name = "id_rol", nullable = false)),
			@AttributeOverride(name = "idMenu", column = @Column(name = "id_menu", nullable = false)) })
	public PermisoMenuId getId() {
		return this.id;
	}

	public void setId(PermisoMenuId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_menu", nullable = false, insertable = false, updatable = false)
	public Menu getMenu() {
		return this.menu;
	}

	public void setMenu(Menu menu) {
		this.menu = menu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_rol", nullable = false, insertable = false, updatable = false)
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	@Column(name = "can_create", nullable = false)
	public boolean isCanCreate() {
		return this.canCreate;
	}

	public void setCanCreate(boolean canCreate) {
		this.canCreate = canCreate;
	}

	@Column(name = "can_read", nullable = false)
	public boolean isCanRead() {
		return this.canRead;
	}

	public void setCanRead(boolean canRead) {
		this.canRead = canRead;
	}

	@Column(name = "can_update", nullable = false)
	public boolean isCanUpdate() {
		return this.canUpdate;
	}

	public void setCanUpdate(boolean canUpdate) {
		this.canUpdate = canUpdate;
	}

	@Column(name = "can_delete", nullable = false)
	public boolean isCanDelete() {
		return this.canDelete;
	}

	public void setCanDelete(boolean canDelete) {
		this.canDelete = canDelete;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_registro", nullable = false, length = 23)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "usuario_registro", nullable = false, length = 10)
	public String getUsuarioRegistro() {
		return this.usuarioRegistro;
	}

	public void setUsuarioRegistro(String usuarioRegistro) {
		this.usuarioRegistro = usuarioRegistro;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modifico", length = 23)
	public Date getFechaModifico() {
		return this.fechaModifico;
	}

	public void setFechaModifico(Date fechaModifico) {
		this.fechaModifico = fechaModifico;
	}

	@Column(name = "usuario_modifico", length = 10)
	public String getUsuarioModifico() {
		return this.usuarioModifico;
	}

	public void setUsuarioModifico(String usuarioModifico) {
		this.usuarioModifico = usuarioModifico;
	}

}
