package lcb.com.pe.domain;
// Generated 21/02/2017 12:52:07 PM by Hibernate Tools 5.0.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Repositorio generated by hbm2java
 */
@Entity
@Table(name = "Repositorio", schema = "dbo", catalog = "LCB_SECURITY")
public class Repositorio implements java.io.Serializable {

	private Integer idRepositorio;
	private Sistema sistema;
	private String nombre;
	private String usuarioRegistro;
	private Date fechaRegistro;
	private Set<PermisoRepositorio> permisoRepositorios = new HashSet<PermisoRepositorio>(0);

	public Repositorio() {
	}

	public Repositorio(Sistema sistema, String nombre, String usuarioRegistro, Date fechaRegistro) {
		this.sistema = sistema;
		this.nombre = nombre;
		this.usuarioRegistro = usuarioRegistro;
		this.fechaRegistro = fechaRegistro;
	}

	public Repositorio(Sistema sistema, String nombre, String usuarioRegistro, Date fechaRegistro,
			Set<PermisoRepositorio> permisoRepositorios) {
		this.sistema = sistema;
		this.nombre = nombre;
		this.usuarioRegistro = usuarioRegistro;
		this.fechaRegistro = fechaRegistro;
		this.permisoRepositorios = permisoRepositorios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_repositorio", unique = true, nullable = false)
	public Integer getIdRepositorio() {
		return this.idRepositorio;
	}

	public void setIdRepositorio(Integer idRepositorio) {
		this.idRepositorio = idRepositorio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_sistema", nullable = false)
	public Sistema getSistema() {
		return this.sistema;
	}

	public void setSistema(Sistema sistema) {
		this.sistema = sistema;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "usuario_registro", nullable = false, length = 10)
	public String getUsuarioRegistro() {
		return this.usuarioRegistro;
	}

	public void setUsuarioRegistro(String usuarioRegistro) {
		this.usuarioRegistro = usuarioRegistro;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_registro", nullable = false, length = 23)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "repositorio")
	public Set<PermisoRepositorio> getPermisoRepositorios() {
		return this.permisoRepositorios;
	}

	public void setPermisoRepositorios(Set<PermisoRepositorio> permisoRepositorios) {
		this.permisoRepositorios = permisoRepositorios;
	}

}
