package lcb.com.pe.domain;
// Generated 21/02/2017 12:52:07 PM by Hibernate Tools 5.0.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name = "Rol", schema = "dbo", catalog = "LCB_SECURITY")
public class Rol implements java.io.Serializable {

	private Short idRol;
	private Sistema sistema;
	private String descripcion;
	private String usuarioRegistro;
	private Date fechaRegistro;
	private Set<PermisoMenu> permisoMenus = new HashSet<PermisoMenu>(0);
	private Set<UsuarioSistema> usuarioSistemas = new HashSet<UsuarioSistema>(0);
	private Set<PermisoRepositorio> permisoRepositorios = new HashSet<PermisoRepositorio>(0);

	public Rol() {
	}

	public Rol(Sistema sistema, String descripcion, String usuarioRegistro, Date fechaRegistro) {
		this.sistema = sistema;
		this.descripcion = descripcion;
		this.usuarioRegistro = usuarioRegistro;
		this.fechaRegistro = fechaRegistro;
	}

	public Rol(Sistema sistema, String descripcion, String usuarioRegistro, Date fechaRegistro, Set<PermisoMenu> permisoMenus,
			Set<UsuarioSistema> usuarioSistemas, Set<PermisoRepositorio> permisoRepositorios) {
		this.sistema = sistema;
		this.descripcion = descripcion;
		this.usuarioRegistro = usuarioRegistro;
		this.fechaRegistro = fechaRegistro;
		this.permisoMenus = permisoMenus;
		this.usuarioSistemas = usuarioSistemas;
		this.permisoRepositorios = permisoRepositorios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_rol", unique = true, nullable = false)
	public Short getIdRol() {
		return this.idRol;
	}

	public void setIdRol(Short idRol) {
		this.idRol = idRol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_sistema", nullable = false)
	public Sistema getSistema() {
		return this.sistema;
	}

	public void setSistema(Sistema sistema) {
		this.sistema = sistema;
	}

	@Column(name = "descripcion", nullable = false, length = 20)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "usuario_registro", nullable = false, length = 10)
	public String getUsuarioRegistro() {
		return this.usuarioRegistro;
	}

	public void setUsuarioRegistro(String usuarioRegistro) {
		this.usuarioRegistro = usuarioRegistro;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_registro", nullable = false, length = 23)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
	public Set<PermisoMenu> getPermisoMenus() {
		return this.permisoMenus;
	}

	public void setPermisoMenus(Set<PermisoMenu> permisoMenus) {
		this.permisoMenus = permisoMenus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
	public Set<UsuarioSistema> getUsuarioSistemas() {
		return this.usuarioSistemas;
	}

	public void setUsuarioSistemas(Set<UsuarioSistema> usuarioSistemas) {
		this.usuarioSistemas = usuarioSistemas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
	public Set<PermisoRepositorio> getPermisoRepositorios() {
		return this.permisoRepositorios;
	}

	public void setPermisoRepositorios(Set<PermisoRepositorio> permisoRepositorios) {
		this.permisoRepositorios = permisoRepositorios;
	}

}
