package lcb.com.pe.domain;
// Generated 21/02/2017 12:52:07 PM by Hibernate Tools 5.0.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sistema generated by hbm2java
 */
@Entity
@Table(name = "Sistema", schema = "dbo", catalog = "LCB_SECURITY")
public class Sistema implements java.io.Serializable {

	private int idSistema;
	private String descripcion;
	private String siglas;
	private String usuarioRegistro;
	private Date fechaRegistro;
	private Set<Rol> rols = new HashSet<Rol>(0);
	private Set<Menu> menus = new HashSet<Menu>(0);
	private Set<Repositorio> repositorios = new HashSet<Repositorio>(0);

	public Sistema() {
	}

	public Sistema(String descripcion, String siglas, String usuarioRegistro, Date fechaRegistro) {
		this.descripcion = descripcion;
		this.siglas = siglas;
		this.usuarioRegistro = usuarioRegistro;
		this.fechaRegistro = fechaRegistro;
	}

	public Sistema(String descripcion, String siglas, String usuarioRegistro, Date fechaRegistro, Set<Rol> rols, Set<Menu> menus,
			Set<Repositorio> repositorios) {
		this.descripcion = descripcion;
		this.siglas = siglas;
		this.usuarioRegistro = usuarioRegistro;
		this.fechaRegistro = fechaRegistro;
		this.rols = rols;
		this.menus = menus;
		this.repositorios = repositorios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_sistema", unique = true, nullable = false)
	public int getIdSistema() {
		return this.idSistema;
	}

	public void setIdSistema(int idSistema) {
		this.idSistema = idSistema;
	}
	
	@Column(name = "descripcion", nullable = false, length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "siglas", nullable = false, length = 10)
	public String getSiglas() {
		return this.siglas;
	}

	public void setSiglas(String siglas) {
		this.siglas = siglas;
	}

	@Column(name = "usuario_registro", nullable = false, length = 10)
	public String getUsuarioRegistro() {
		return this.usuarioRegistro;
	}

	public void setUsuarioRegistro(String usuarioRegistro) {
		this.usuarioRegistro = usuarioRegistro;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_registro", nullable = false, length = 23)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sistema")
	public Set<Rol> getRols() {
		return this.rols;
	}

	public void setRols(Set<Rol> rols) {
		this.rols = rols;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sistema")
	public Set<Menu> getMenus() {
		return this.menus;
	}

	public void setMenus(Set<Menu> menus) {
		this.menus = menus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sistema")
	public Set<Repositorio> getRepositorios() {
		return this.repositorios;
	}

	public void setRepositorios(Set<Repositorio> repositorios) {
		this.repositorios = repositorios;
	}

}
