package lcb.com.pe.domain;
// Generated 21/02/2017 12:52:07 PM by Hibernate Tools 5.0.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * UsuarioSistema generated by hbm2java
 */
@Entity
@Table(name = "Usuario_Sistema", schema = "dbo", catalog = "LCB_SECURITY", uniqueConstraints = @UniqueConstraint(columnNames = {
		"usuario", "id_rol" }))
public class UsuarioSistema implements java.io.Serializable {

	private Integer idUsuarioRol;
	private Rol rol;
	private Usuario usuario;
	private String rolAutorizacion;
	private short intentos;
	private char estado;
	private String usuarioRegistro;
	private Date fechaRegistro;
	private Date ultimoAcceso;
	private String ipUltimoAcceso;

	public UsuarioSistema() {
	}

	public UsuarioSistema(Rol rol, Usuario usuario, String rolAutorizacion, short intentos, char estado,
			String usuarioRegistro, Date fechaRegistro) {
		this.rol = rol;
		this.usuario = usuario;
		this.rolAutorizacion = rolAutorizacion;
		this.intentos = intentos;
		this.estado = estado;
		this.usuarioRegistro = usuarioRegistro;
		this.fechaRegistro = fechaRegistro;
	}

	public UsuarioSistema(Rol rol, Usuario usuario, String rolAutorizacion, short intentos, char estado,
			String usuarioRegistro, Date fechaRegistro, Date ultimoAcceso, String ipUltimoAcceso) {
		this.rol = rol;
		this.usuario = usuario;
		this.rolAutorizacion = rolAutorizacion;
		this.intentos = intentos;
		this.estado = estado;
		this.usuarioRegistro = usuarioRegistro;
		this.fechaRegistro = fechaRegistro;
		this.ultimoAcceso = ultimoAcceso;
		this.ipUltimoAcceso = ipUltimoAcceso;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_usuario_rol", unique = true, nullable = false)
	public Integer getIdUsuarioRol() {
		return this.idUsuarioRol;
	}

	public void setIdUsuarioRol(Integer idUsuarioRol) {
		this.idUsuarioRol = idUsuarioRol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_rol", nullable = false)
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "rol_autorizacion", nullable = false, length = 10)
	public String getRolAutorizacion() {
		return this.rolAutorizacion;
	}

	public void setRolAutorizacion(String rolAutorizacion) {
		this.rolAutorizacion = rolAutorizacion;
	}

	@Column(name = "intentos", nullable = false)
	public short getIntentos() {
		return this.intentos;
	}

	public void setIntentos(short intentos) {
		this.intentos = intentos;
	}

	@Column(name = "estado", nullable = false, length = 1)
	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

	@Column(name = "usuario_registro", nullable = false, length = 10)
	public String getUsuarioRegistro() {
		return this.usuarioRegistro;
	}

	public void setUsuarioRegistro(String usuarioRegistro) {
		this.usuarioRegistro = usuarioRegistro;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_registro", nullable = false, length = 23)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ultimo_acceso", length = 23)
	public Date getUltimoAcceso() {
		return this.ultimoAcceso;
	}

	public void setUltimoAcceso(Date ultimoAcceso) {
		this.ultimoAcceso = ultimoAcceso;
	}

	@Column(name = "ipultimo_acceso", length = 15)
	public String getIpUltimoAcceso() {
		return this.ipUltimoAcceso;
	}

	public void setIpUltimoAcceso(String ipUltimoAcceso) {
		this.ipUltimoAcceso = ipUltimoAcceso;
	}

}
